name: Feature request
description: Suggest an idea for this project
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: Please describe.
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: What should happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
  - type: textarea
    id: additional
    attributes:
      label: Additional context


